### ISSUE TITLE
java.lang.NullPointerException: null reference

### ISSUE THREAD

**Issue by Sandeep145XamRN** [OvalMoney/react-native-fitness#94]
java.lang.NullPointerException: null reference
        at com.google.android.gms.common.internal.Preconditions.checkNotNull(Unknown Source)
        at com.google.android.gms.fitness.Fitness.getHistoryClient(Unknown Source)
        at com.ovalmoney.fitness.manager.Manager.getCalories(Manager.java:353)
        at com.ovalmoney.fitness.RNFitnessModule.getCalories(RNFitnessModule.java:167)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:754)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:165)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:760)

**Comment by Sandeep145XamRN** [comment]
I'm trying to access getCalories() without authorise .

**Comment by zuhairnaqi** [comment]
@Sandeep145XamRN how you solve this issue?
